provider "aws" {}
provider "azurerm" {}
provider "google" {}
provider "alicloud" {}
provider "helm" {}
provider "kubernetes" {}
provider "random" {}
provider "null" {}
provider "external" {}
provider "template" {}
provider "archive" {}